name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install Dependencies
        run: |
          poetry install
          
      - name: Run Ruff Linting
        run: |
          poetry run ruff check .
          
      - name: Run Ruff Formatting
        run: |
          poetry run ruff format --check .
          
      - name: Run Pyright Type Checking
        run: |
          poetry run pyright
          
      - name: Run Tests
        run: |
          poetry run pytest --cov=flow_metrics
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false